FROM maven:3.9.9-eclipse-temurin-22 AS build
WORKDIR /workspace

COPY pom.xml ./
RUN mvn -B -ntp -DskipTests dependency:go-offline

COPY src ./src
RUN mvn -B -ntp -Dmaven.test.skip=true package

FROM eclipse-temurin:22-jre
WORKDIR /app

COPY --from=build /workspace/target/voktrader-0.0.1-SNAPSHOT.jar /app/voktrader.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/voktrader.jar"]
