package com.vokerg.voktrader.paper;

import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;

@Component
@Deprecated
@Order(Ordered.HIGHEST_PRECEDENCE)
public class SignalSchemaRepair implements ApplicationRunner {

    private final DataSource dataSource;
    private final JdbcTemplate jdbcTemplate;

    public SignalSchemaRepair(DataSource dataSource, JdbcTemplate jdbcTemplate) {
        this.dataSource = dataSource;
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(ApplicationArguments args) throws Exception {
        try (Connection connection = dataSource.getConnection()) {
            if (!connection.getMetaData().getURL().startsWith("jdbc:h2:")) {
                return;
            }
        }

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS signals (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    market_id VARCHAR(255) NOT NULL,
                    market_slug VARCHAR(255),
                    question VARCHAR(1000),
                    outcome VARCHAR(255) NOT NULL,
                    token_id VARCHAR(100) NOT NULL,
                    signal_type VARCHAR(20) NOT NULL,
                    entry_price NUMERIC(19, 8) NOT NULL,
                    size_usd NUMERIC(19, 8) NOT NULL,
                    shares NUMERIC(19, 8) NOT NULL,
                    decision_bid NUMERIC(19, 8),
                    decision_ask NUMERIC(19, 8),
                    decision_spread NUMERIC(19, 8),
                    decision_price_updated_at TIMESTAMP WITH TIME ZONE,
                    snapshot_age_ms BIGINT,
                    fee_rate NUMERIC(19, 8),
                    entry_fee_usd NUMERIC(19, 8),
                    exit_fee_usd NUMERIC(19, 8),
                    total_fee_usd NUMERIC(19, 8),
                    gross_shares NUMERIC(19, 8),
                    net_shares NUMERIC(19, 8),
                    rule_name VARCHAR(255) NOT NULL,
                    reason VARCHAR(1000),
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    market_end_date TIMESTAMP WITH TIME ZONE,
                    status VARCHAR(20) NOT NULL,
                    resolved_at TIMESTAMP WITH TIME ZONE,
                    winning_outcome VARCHAR(255),
                    pnl_usd NUMERIC(19, 8),
                    exit_price NUMERIC(19, 8),
                    exit_value_usd NUMERIC(19, 8),
                    exit_reason VARCHAR(1000)
                )
                """);
        if (tableExists("FAKE_SIGNALS")) {
            jdbcTemplate.execute("""
                    INSERT INTO signals (
                        market_id,
                        market_slug,
                        question,
                        outcome,
                        token_id,
                        signal_type,
                        entry_price,
                        size_usd,
                        shares,
                        fee_rate,
                        entry_fee_usd,
                        gross_shares,
                        net_shares,
                        rule_name,
                        reason,
                        created_at,
                        market_end_date,
                        status,
                        resolved_at,
                        winning_outcome,
                        pnl_usd,
                        exit_price,
                        exit_value_usd,
                        exit_reason
                    )
                    SELECT
                        old.market_id,
                        old.market_slug,
                        old.question,
                        old.outcome,
                        old.token_id,
                        'PAPER',
                        old.entry_price,
                        old.fake_size_usd,
                        COALESCE(old.net_fake_shares, old.fake_shares),
                        COALESCE(old.fee_rate, 0),
                        COALESCE(old.entry_fee_usd, 0),
                        COALESCE(old.gross_fake_shares, old.fake_shares),
                        COALESCE(old.net_fake_shares, old.fake_shares),
                        old.rule_name,
                        old.reason,
                        old.created_at,
                        old.market_end_date,
                        old.status,
                        old.resolved_at,
                        old.winning_outcome,
                        old.fake_pnl,
                        old.exit_price,
                        old.exit_value_usd,
                        old.exit_reason
                    FROM fake_signals old
                    WHERE NOT EXISTS (
                        SELECT 1
                        FROM signals current
                        WHERE current.market_id = old.market_id
                          AND current.token_id = old.token_id
                          AND current.rule_name = old.rule_name
                          AND current.signal_type = 'PAPER'
                    )
                    """);
            jdbcTemplate.execute("DROP TABLE fake_signals");
        }
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ALTER COLUMN status SET DATA TYPE VARCHAR(20)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ALTER COLUMN status SET NOT NULL");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ALTER COLUMN signal_type SET DATA TYPE VARCHAR(20)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ALTER COLUMN signal_type SET NOT NULL");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ADD COLUMN IF NOT EXISTS size_usd NUMERIC(19, 8)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ADD COLUMN IF NOT EXISTS shares NUMERIC(19, 8)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ADD COLUMN IF NOT EXISTS gross_shares NUMERIC(19, 8)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ADD COLUMN IF NOT EXISTS net_shares NUMERIC(19, 8)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ADD COLUMN IF NOT EXISTS pnl_usd NUMERIC(19, 8)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ADD COLUMN IF NOT EXISTS exit_fee_usd NUMERIC(19, 8)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ADD COLUMN IF NOT EXISTS total_fee_usd NUMERIC(19, 8)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ADD COLUMN IF NOT EXISTS decision_bid NUMERIC(19, 8)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ADD COLUMN IF NOT EXISTS decision_ask NUMERIC(19, 8)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ADD COLUMN IF NOT EXISTS decision_spread NUMERIC(19, 8)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ADD COLUMN IF NOT EXISTS decision_price_updated_at TIMESTAMP WITH TIME ZONE");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals ADD COLUMN IF NOT EXISTS snapshot_age_ms BIGINT");
        jdbcTemplate.execute("UPDATE signals SET shares = net_shares WHERE shares IS NULL AND net_shares IS NOT NULL");
        jdbcTemplate.execute("UPDATE signals SET size_usd = gross_shares * entry_price WHERE size_usd IS NULL AND gross_shares IS NOT NULL AND entry_price IS NOT NULL");
        jdbcTemplate.execute("UPDATE signals SET size_usd = 1.00 WHERE size_usd IS NULL AND signal_type = 'PAPER'");
        jdbcTemplate.execute("UPDATE signals SET gross_shares = size_usd / entry_price WHERE gross_shares IS NULL AND size_usd IS NOT NULL AND entry_price IS NOT NULL AND entry_price > 0");
        jdbcTemplate.execute("UPDATE signals SET net_shares = gross_shares WHERE net_shares IS NULL AND gross_shares IS NOT NULL");
        jdbcTemplate.execute("UPDATE signals SET shares = net_shares WHERE shares IS NULL AND net_shares IS NOT NULL");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals DROP COLUMN IF EXISTS paper_size_usd");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals DROP COLUMN IF EXISTS paper_shares");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals DROP COLUMN IF EXISTS gross_paper_shares");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals DROP COLUMN IF EXISTS net_paper_shares");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS signals DROP COLUMN IF EXISTS paper_pnl");
    }

    private boolean tableExists(String tableName) {
        Integer count = jdbcTemplate.queryForObject(
                """
                        SELECT COUNT(*)
                        FROM information_schema.tables
                        WHERE table_schema = 'PUBLIC'
                          AND table_name = ?
                        """,
                Integer.class,
                tableName
        );

        return count != null && count > 0;
    }
}
