package com.vokerg.voktrader.api.trade.dto;

import com.vokerg.voktrader.trade.model.ExecutionMode;
import com.vokerg.voktrader.trade.model.TradeEntity;
import com.vokerg.voktrader.trade.model.TradeOrderType;
import com.vokerg.voktrader.trade.model.TradeSide;
import com.vokerg.voktrader.trade.model.TradeStatus;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

public record TradeDetailResponse(
        Long id,
        Long botId,
        ExecutionMode mode,
        String strategyId,
        String ruleId,
        String marketId,
        String marketSlug,
        String question,
        String conditionId,
        String tokenId,
        String outcome,
        TradeStatus status,
        TradeSide decisionSide,
        String decisionReason,
        Instant decisionAt,
        Instant marketEndAt,
        Long secondsToExpiryAtDecision,
        BigDecimal observedBid,
        BigDecimal observedAsk,
        BigDecimal observedSpread,
        BigDecimal observedMidpoint,
        Instant priceUpdatedAt,
        Long priceAgeMs,
        BigDecimal intendedAmountUsd,
        BigDecimal intendedShares,
        BigDecimal intendedEntryPrice,
        BigDecimal intendedExitPrice,
        BigDecimal maxSlippagePrice,
        TradeOrderType entryOrderType,
        BigDecimal entryAvgPrice,
        BigDecimal entryFilledShares,
        BigDecimal entryFilledUsd,
        BigDecimal entryFeeUsd,
        Instant entryCompletedAt,
        BigDecimal exitAvgPrice,
        BigDecimal exitFilledShares,
        BigDecimal exitFilledUsd,
        BigDecimal exitFeeUsd,
        Instant exitCompletedAt,
        BigDecimal totalFeeUsd,
        BigDecimal realizedPnlUsd,
        BigDecimal resolvedPnlUsd,
        BigDecimal finalPnlUsd,
        String winningOutcome,
        Instant resolvedAt,
        String backtestRunId,
        Instant createdAt,
        Instant updatedAt,
        List<TradeFillResponse> fills,
        List<TradeOrderResponse> orders,
        List<TradeEventResponse> events
) {
    public static TradeDetailResponse from(
            TradeEntity entity,
            List<TradeFillResponse> fills,
            List<TradeOrderResponse> orders,
            List<TradeEventResponse> events
    ) {
        return new TradeDetailResponse(
                entity.getId(),
                entity.getBotId(),
                entity.getMode(),
                entity.getStrategyId(),
                entity.getRuleId(),
                entity.getMarketId(),
                entity.getMarketSlug(),
                entity.getQuestion(),
                entity.getConditionId(),
                entity.getTokenId(),
                entity.getOutcome(),
                entity.getStatus(),
                entity.getDecisionSide(),
                entity.getDecisionReason(),
                entity.getDecisionAt(),
                entity.getMarketEndAt(),
                entity.getSecondsToExpiryAtDecision(),
                entity.getObservedBid(),
                entity.getObservedAsk(),
                entity.getObservedSpread(),
                entity.getObservedMidpoint(),
                entity.getPriceUpdatedAt(),
                entity.getPriceAgeMs(),
                entity.getIntendedAmountUsd(),
                entity.getIntendedShares(),
                entity.getIntendedEntryPrice(),
                entity.getIntendedExitPrice(),
                entity.getMaxSlippagePrice(),
                entity.getEntryOrderType(),
                entity.getEntryAvgPrice(),
                entity.getEntryFilledShares(),
                entity.getEntryFilledUsd(),
                entity.getEntryFeeUsd(),
                entity.getEntryCompletedAt(),
                entity.getExitAvgPrice(),
                entity.getExitFilledShares(),
                entity.getExitFilledUsd(),
                entity.getExitFeeUsd(),
                entity.getExitCompletedAt(),
                entity.getTotalFeeUsd(),
                entity.getRealizedPnlUsd(),
                entity.getResolvedPnlUsd(),
                entity.getFinalPnlUsd(),
                entity.getWinningOutcome(),
                entity.getResolvedAt(),
                entity.getBacktestRunId(),
                entity.getCreatedAt(),
                entity.getUpdatedAt(),
                fills,
                orders,
                events
        );
    }
}
