CREATE TABLE IF NOT EXISTS bot_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    enabled BOOLEAN NOT NULL,
    market_family VARCHAR(32) NOT NULL,
    strategy_id VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    last_error VARCHAR(4000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bot_configs_enabled ON bot_configs(enabled);
CREATE INDEX IF NOT EXISTS idx_bot_configs_family ON bot_configs(market_family);

CREATE TABLE IF NOT EXISTS bot_market_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id BIGINT NOT NULL,
    market_id VARCHAR(255) NOT NULL,
    market_slug VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    stopped_at TIMESTAMP,
    resolved_at TIMESTAMP,
    CONSTRAINT fk_bot_market_runs_bot FOREIGN KEY (bot_id) REFERENCES bot_configs(id)
);

CREATE INDEX IF NOT EXISTS idx_bot_market_runs_bot_status ON bot_market_runs(bot_id, status);
CREATE INDEX IF NOT EXISTS idx_bot_market_runs_market ON bot_market_runs(market_id);

ALTER TABLE trades ADD COLUMN IF NOT EXISTS bot_id BIGINT;
ALTER TABLE trade_orders ADD COLUMN IF NOT EXISTS bot_id BIGINT;
ALTER TABLE trade_events ADD COLUMN IF NOT EXISTS bot_id BIGINT;
ALTER TABLE trade_fills ADD COLUMN IF NOT EXISTS bot_id BIGINT;
ALTER TABLE trade_risk_checks ADD COLUMN IF NOT EXISTS bot_id BIGINT;
ALTER TABLE price_snapshots ADD COLUMN IF NOT EXISTS bot_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_trades_bot_market_status ON trades(bot_id, market_id, status);
CREATE INDEX IF NOT EXISTS idx_trades_bot_strategy_market ON trades(bot_id, strategy_id, market_id);
CREATE INDEX IF NOT EXISTS idx_trade_orders_bot ON trade_orders(bot_id);
CREATE INDEX IF NOT EXISTS idx_trade_events_bot ON trade_events(bot_id);
CREATE INDEX IF NOT EXISTS idx_trade_fills_bot ON trade_fills(bot_id);
CREATE INDEX IF NOT EXISTS idx_trade_risk_checks_bot ON trade_risk_checks(bot_id);
