CREATE TABLE IF NOT EXISTS market_depth_snapshot_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_entity_id BIGINT,
    market_id BIGINT,
    remaining_seconds BIGINT,
    outcome VARCHAR(128),
    token_id VARCHAR(128),
    side VARCHAR(16),
    level_index INTEGER,
    price NUMERIC(19, 8),
    size NUMERIC(19, 8),
    book_updated_at TIMESTAMP,
    captured_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_market_depth_snapshot_levels_market_captured
    ON market_depth_snapshot_levels (market_id, captured_at);

CREATE INDEX IF NOT EXISTS idx_market_depth_snapshot_levels_token_captured
    ON market_depth_snapshot_levels (token_id, captured_at);

CREATE INDEX IF NOT EXISTS idx_market_depth_snapshot_levels_book
    ON market_depth_snapshot_levels (market_id, captured_at, token_id, side, level_index);
