ALTER TABLE trades ALTER COLUMN status VARCHAR(32);
ALTER TABLE trades ALTER COLUMN mode VARCHAR(32);
ALTER TABLE trades ALTER COLUMN decision_side VARCHAR(16);
ALTER TABLE trades ALTER COLUMN entry_order_type VARCHAR(32);

ALTER TABLE trade_orders ALTER COLUMN phase VARCHAR(32);
ALTER TABLE trade_orders ALTER COLUMN mode VARCHAR(32);
ALTER TABLE trade_orders ALTER COLUMN venue VARCHAR(32);
ALTER TABLE trade_orders ALTER COLUMN side VARCHAR(16);
ALTER TABLE trade_orders ALTER COLUMN order_type VARCHAR(32);
ALTER TABLE trade_orders ALTER COLUMN status VARCHAR(32);

ALTER TABLE trade_risk_checks ALTER COLUMN mode VARCHAR(32);
ALTER TABLE trade_risk_checks ALTER COLUMN severity VARCHAR(16);
