ALTER TABLE trades ALTER COLUMN status SET DATA TYPE VARCHAR(32);
ALTER TABLE trades ALTER COLUMN mode SET DATA TYPE VARCHAR(32);
ALTER TABLE trades ALTER COLUMN decision_side SET DATA TYPE VARCHAR(16);
ALTER TABLE trades ALTER COLUMN entry_order_type SET DATA TYPE VARCHAR(32);

ALTER TABLE trade_orders ALTER COLUMN phase SET DATA TYPE VARCHAR(32);
ALTER TABLE trade_orders ALTER COLUMN mode SET DATA TYPE VARCHAR(32);
ALTER TABLE trade_orders ALTER COLUMN venue SET DATA TYPE VARCHAR(32);
ALTER TABLE trade_orders ALTER COLUMN side SET DATA TYPE VARCHAR(16);
ALTER TABLE trade_orders ALTER COLUMN order_type SET DATA TYPE VARCHAR(32);
ALTER TABLE trade_orders ALTER COLUMN status SET DATA TYPE VARCHAR(32);

ALTER TABLE trade_risk_checks ALTER COLUMN mode SET DATA TYPE VARCHAR(32);
ALTER TABLE trade_risk_checks ALTER COLUMN severity SET DATA TYPE VARCHAR(16);
