CREATE TABLE tick_size_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_id VARCHAR(128) NOT NULL,
    market_id VARCHAR(128),
    tick_size DECIMAL(19, 8) NOT NULL,
    effective_at TIMESTAMP WITH TIME ZONE NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    source VARCHAR(32) NOT NULL
);

CREATE INDEX idx_tick_size_token_effective
    ON tick_size_metadata (token_id, effective_at);

CREATE INDEX idx_tick_size_market_effective
    ON tick_size_metadata (market_id, effective_at);
