ALTER TABLE markets ADD COLUMN IF NOT EXISTS resolution_source VARCHAR(255);

CREATE TABLE IF NOT EXISTS outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(64) NOT NULL,
    payload_json TEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    aggregate_type VARCHAR(128) NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE,
    attempts INT NOT NULL,
    last_error VARCHAR(2000),
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_outbox_events_idempotency_key UNIQUE (idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_outbox_events_pending
    ON outbox_events (type, status, next_attempt_at, created_at);

CREATE INDEX IF NOT EXISTS idx_outbox_events_aggregate
    ON outbox_events (aggregate_type, aggregate_id);
