CREATE TABLE IF NOT EXISTS historical_tick_coverage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_type VARCHAR(32) NOT NULL,
    market_id BIGINT,
    token_id VARCHAR(128),
    interval_start_at TIMESTAMP NOT NULL,
    interval_end_at TIMESTAMP NOT NULL,
    tick_size NUMERIC(19, 8),
    coverage_status VARCHAR(16) NOT NULL,
    evidence_source VARCHAR(40) NOT NULL,
    source_reference TEXT,
    blocker_reason TEXT,
    recorded_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_historical_tick_interval_order
        CHECK (interval_end_at >= interval_start_at),
    CONSTRAINT chk_historical_tick_coverage_evidence
        CHECK (
            (coverage_status = 'RESOLVED'
                AND token_id IS NOT NULL
                AND token_id <> ''
                AND tick_size IS NOT NULL
                AND tick_size > 0
                AND evidence_source <> 'UNRESOLVED'
                AND source_reference IS NOT NULL
                AND source_reference <> ''
                AND blocker_reason IS NULL)
            OR
            (coverage_status = 'BLOCKED'
                AND tick_size IS NULL
                AND evidence_source = 'UNRESOLVED'
                AND source_reference IS NULL
                AND blocker_reason IS NOT NULL
                AND blocker_reason <> '')
        )
);

CREATE INDEX IF NOT EXISTS idx_historical_tick_coverage_interval
    ON historical_tick_coverage (
        dataset_type,
        market_id,
        token_id,
        interval_start_at,
        interval_end_at,
        coverage_status
    );

CREATE INDEX IF NOT EXISTS idx_historical_tick_coverage_token_interval
    ON historical_tick_coverage (token_id, interval_start_at, interval_end_at);

CREATE INDEX IF NOT EXISTS idx_historical_tick_coverage_status
    ON historical_tick_coverage (coverage_status, dataset_type);
