CREATE TABLE IF NOT EXISTS order_intents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_order_id VARCHAR(128) NOT NULL,
    intent_hash VARCHAR(64) NOT NULL,
    risk_decision_id VARCHAR(255) NOT NULL,
    execution_mode VARCHAR(16) NOT NULL,
    side VARCHAR(16) NOT NULL,
    state VARCHAR(32) NOT NULL,
    payload_json TEXT NOT NULL,
    accepted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_order_intents_client_order_id UNIQUE (client_order_id),
    CONSTRAINT ck_order_intents_execution_mode
        CHECK (execution_mode IN ('BACKTEST', 'PAPER', 'LIVE')),
    CONSTRAINT ck_order_intents_side
        CHECK (side IN ('BUY', 'SELL')),
    CONSTRAINT ck_order_intents_state
        CHECK (state IN ('ACCEPTED', 'DISPATCHED', 'REJECTED', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_order_intents_risk_decision
    ON order_intents (risk_decision_id, accepted_at);

CREATE INDEX IF NOT EXISTS idx_order_intents_hash
    ON order_intents (intent_hash);

CREATE TABLE IF NOT EXISTS order_dispatch_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_intent_id BIGINT NOT NULL,
    client_order_id VARCHAR(128) NOT NULL,
    state VARCHAR(32) NOT NULL,
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    lease_owner VARCHAR(128),
    lease_expires_at TIMESTAMP WITH TIME ZONE,
    last_attempt_at TIMESTAMP WITH TIME ZONE,
    submitted_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    remote_order_id VARCHAR(255),
    unknown_outcome_at TIMESTAMP WITH TIME ZONE,
    unknown_outcome_reason VARCHAR(255),
    unknown_outcome_details TEXT,
    last_error VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_order_dispatch_outbox_intent
        FOREIGN KEY (order_intent_id) REFERENCES order_intents (id),
    CONSTRAINT uk_order_dispatch_outbox_intent UNIQUE (order_intent_id),
    CONSTRAINT uk_order_dispatch_outbox_client_order_id UNIQUE (client_order_id),
    CONSTRAINT ck_order_dispatch_outbox_state
        CHECK (state IN (
            'OUTBOX_READY',
            'SUBMITTING',
            'SUBMITTED',
            'UNKNOWN',
            'RECONCILE',
            'MANUAL_REVIEW',
            'COMPLETED',
            'FAILED',
            'CANCELLED'
        )),
    CONSTRAINT ck_order_dispatch_outbox_attempts
        CHECK (attempts >= 0),
    CONSTRAINT ck_order_dispatch_outbox_lease
        CHECK (
            (lease_owner IS NULL AND lease_expires_at IS NULL)
            OR (lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)
        )
);

CREATE INDEX IF NOT EXISTS idx_order_dispatch_outbox_ready
    ON order_dispatch_outbox (state, next_attempt_at, created_at);

CREATE INDEX IF NOT EXISTS idx_order_dispatch_outbox_lease
    ON order_dispatch_outbox (state, lease_expires_at);
