CREATE TABLE IF NOT EXISTS user_websocket_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dedupe_key VARCHAR(192) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    remote_event_id VARCHAR(255),
    remote_order_id VARCHAR(255),
    remote_trade_id VARCHAR(255),
    market_id VARCHAR(255),
    token_id VARCHAR(255),
    side VARCHAR(16),
    lifecycle_status VARCHAR(64),
    event_timestamp TIMESTAMP WITH TIME ZONE,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    connection_generation BIGINT NOT NULL,
    raw_payload TEXT NOT NULL,
    processed BOOLEAN NOT NULL DEFAULT FALSE,
    processing_note TEXT,
    trade_order_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_user_ws_events_dedupe UNIQUE (dedupe_key),
    CONSTRAINT fk_user_ws_events_trade_order
        FOREIGN KEY (trade_order_id) REFERENCES trade_orders (id)
);

CREATE INDEX IF NOT EXISTS idx_user_ws_events_order
    ON user_websocket_events (remote_order_id, received_at);

CREATE INDEX IF NOT EXISTS idx_user_ws_events_trade
    ON user_websocket_events (remote_trade_id, received_at);

CREATE INDEX IF NOT EXISTS idx_user_ws_events_received
    ON user_websocket_events (received_at);

ALTER TABLE trade_orders
    ADD COLUMN IF NOT EXISTS last_user_ws_event_type VARCHAR(32),
    ADD COLUMN IF NOT EXISTS last_user_ws_status VARCHAR(64),
    ADD COLUMN IF NOT EXISTS last_user_ws_trade_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS last_user_ws_event_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS last_user_ws_generation BIGINT;
