CREATE TABLE IF NOT EXISTS trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode VARCHAR(32) NOT NULL,
    strategy_id VARCHAR(255) NOT NULL,
    rule_id VARCHAR(255),
    market_id VARCHAR(255) NOT NULL,
    market_slug VARCHAR(255),
    question VARCHAR(1000),
    condition_id VARCHAR(255),
    token_id VARCHAR(120) NOT NULL,
    outcome VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    decision_side VARCHAR(16) NOT NULL,
    decision_reason VARCHAR(2000),
    decision_at TIMESTAMP NOT NULL,
    market_end_at TIMESTAMP,
    seconds_to_expiry_at_decision BIGINT,
    observed_bid NUMERIC(19, 8),
    observed_ask NUMERIC(19, 8),
    observed_spread NUMERIC(19, 8),
    observed_midpoint NUMERIC(19, 8),
    price_updated_at TIMESTAMP,
    price_age_ms BIGINT,
    intended_amount_usd NUMERIC(19, 8),
    intended_shares NUMERIC(19, 8),
    intended_entry_price NUMERIC(19, 8),
    intended_exit_price NUMERIC(19, 8),
    max_slippage_price NUMERIC(19, 8),
    entry_order_type VARCHAR(32),
    entry_avg_price NUMERIC(19, 8),
    entry_filled_shares NUMERIC(19, 8),
    entry_filled_usd NUMERIC(19, 8),
    entry_fee_usd NUMERIC(19, 8),
    entry_completed_at TIMESTAMP,
    exit_avg_price NUMERIC(19, 8),
    exit_filled_shares NUMERIC(19, 8),
    exit_filled_usd NUMERIC(19, 8),
    exit_fee_usd NUMERIC(19, 8),
    exit_completed_at TIMESTAMP,
    total_fee_usd NUMERIC(19, 8),
    realized_pnl_usd NUMERIC(19, 8),
    resolved_pnl_usd NUMERIC(19, 8),
    final_pnl_usd NUMERIC(19, 8),
    winning_outcome VARCHAR(255),
    resolved_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_trades_market_status ON trades (market_id, status);
CREATE INDEX IF NOT EXISTS idx_trades_strategy ON trades (strategy_id);
CREATE INDEX IF NOT EXISTS idx_trades_token ON trades (token_id);

CREATE TABLE IF NOT EXISTS trade_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id BIGINT NOT NULL,
    phase VARCHAR(32) NOT NULL,
    mode VARCHAR(32) NOT NULL,
    venue VARCHAR(32) NOT NULL,
    side VARCHAR(16) NOT NULL,
    order_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    client_order_id VARCHAR(255),
    exchange_order_id VARCHAR(255),
    token_id VARCHAR(120) NOT NULL,
    outcome VARCHAR(255) NOT NULL,
    observed_bid NUMERIC(19, 8),
    observed_ask NUMERIC(19, 8),
    observed_spread NUMERIC(19, 8),
    observed_midpoint NUMERIC(19, 8),
    price_updated_at TIMESTAMP,
    price_age_ms BIGINT,
    expected_price NUMERIC(19, 8),
    limit_price NUMERIC(19, 8),
    requested_amount_usd NUMERIC(19, 8),
    requested_shares NUMERIC(19, 8),
    filled_shares NUMERIC(19, 8),
    filled_amount_usd NUMERIC(19, 8),
    avg_fill_price NUMERIC(19, 8),
    expected_fee_usd NUMERIC(19, 8),
    actual_fee_usd NUMERIC(19, 8),
    expected_slippage NUMERIC(19, 8),
    actual_slippage NUMERIC(19, 8),
    submitted_at TIMESTAMP,
    acknowledged_at TIMESTAMP,
    completed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    latency_ms BIGINT,
    cancel_reason VARCHAR(1000),
    reject_reason VARCHAR(1000),
    error_message VARCHAR(2000),
    raw_request TEXT,
    raw_response TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_trade_orders_trade FOREIGN KEY (trade_id) REFERENCES trades(id),
    CONSTRAINT uk_trade_orders_idempotency_key UNIQUE (idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_trade_orders_trade ON trade_orders (trade_id);
CREATE INDEX IF NOT EXISTS idx_trade_orders_exchange ON trade_orders (exchange_order_id);
CREATE INDEX IF NOT EXISTS idx_trade_orders_status ON trade_orders (status);

CREATE TABLE IF NOT EXISTS trade_fills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id BIGINT NOT NULL,
    trade_order_id BIGINT NOT NULL,
    venue VARCHAR(32) NOT NULL,
    exchange_trade_id VARCHAR(255),
    exchange_order_id VARCHAR(255),
    transaction_hash VARCHAR(255),
    side VARCHAR(16) NOT NULL,
    price NUMERIC(19, 8) NOT NULL,
    shares NUMERIC(19, 8) NOT NULL,
    amount_usd NUMERIC(19, 8) NOT NULL,
    fee_usd NUMERIC(19, 8),
    liquidity_role VARCHAR(255),
    occurred_at TIMESTAMP NOT NULL,
    received_at TIMESTAMP NOT NULL,
    raw_fill TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_trade_fills_trade FOREIGN KEY (trade_id) REFERENCES trades(id),
    CONSTRAINT fk_trade_fills_order FOREIGN KEY (trade_order_id) REFERENCES trade_orders(id)
);

CREATE INDEX IF NOT EXISTS idx_trade_fills_trade ON trade_fills (trade_id);
CREATE INDEX IF NOT EXISTS idx_trade_fills_order ON trade_fills (trade_order_id);
CREATE INDEX IF NOT EXISTS idx_trade_fills_exchange_trade ON trade_fills (exchange_trade_id);

CREATE TABLE IF NOT EXISTS trade_risk_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id BIGINT,
    trade_order_id BIGINT,
    mode VARCHAR(32) NOT NULL,
    check_name VARCHAR(255) NOT NULL,
    passed BOOLEAN NOT NULL,
    severity VARCHAR(16) NOT NULL,
    observed_value VARCHAR(500),
    limit_value VARCHAR(500),
    message VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_trade_risk_checks_trade FOREIGN KEY (trade_id) REFERENCES trades(id),
    CONSTRAINT fk_trade_risk_checks_order FOREIGN KEY (trade_order_id) REFERENCES trade_orders(id)
);

CREATE INDEX IF NOT EXISTS idx_trade_risk_checks_trade ON trade_risk_checks (trade_id);
CREATE INDEX IF NOT EXISTS idx_trade_risk_checks_order ON trade_risk_checks (trade_order_id);
CREATE INDEX IF NOT EXISTS idx_trade_risk_checks_name ON trade_risk_checks (check_name);

CREATE TABLE IF NOT EXISTS trade_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id BIGINT,
    trade_order_id BIGINT,
    trade_fill_id BIGINT,
    event_type VARCHAR(255) NOT NULL,
    message VARCHAR(2000),
    payload_json TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_trade_events_trade FOREIGN KEY (trade_id) REFERENCES trades(id),
    CONSTRAINT fk_trade_events_order FOREIGN KEY (trade_order_id) REFERENCES trade_orders(id),
    CONSTRAINT fk_trade_events_fill FOREIGN KEY (trade_fill_id) REFERENCES trade_fills(id)
);

CREATE INDEX IF NOT EXISTS idx_trade_events_trade ON trade_events (trade_id);
CREATE INDEX IF NOT EXISTS idx_trade_events_type ON trade_events (event_type);
