CREATE TABLE IF NOT EXISTS markets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    polymarket_market_id VARCHAR(255) NOT NULL,
    condition_id VARCHAR(255),
    question VARCHAR(1000),
    slug VARCHAR(255),
    end_date TIMESTAMP WITH TIME ZONE,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    closed BOOLEAN NOT NULL DEFAULT FALSE,
    accepting_orders BOOLEAN NOT NULL DEFAULT FALSE,
    resolved BOOLEAN,
    winning_outcome VARCHAR(255),
    winning_asset_id VARCHAR(255),
    resolved_at TIMESTAMP WITH TIME ZONE,
    first_seen_at TIMESTAMP WITH TIME ZONE,
    last_seen_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_markets_polymarket_market_id UNIQUE (polymarket_market_id)
);
