ALTER TABLE IF EXISTS fake_signals ADD COLUMN IF NOT EXISTS exit_price NUMERIC(19, 8);
ALTER TABLE IF EXISTS fake_signals ADD COLUMN IF NOT EXISTS exit_value_usd NUMERIC(19, 8);
ALTER TABLE IF EXISTS fake_signals ADD COLUMN IF NOT EXISTS exit_reason VARCHAR(1000);
