CREATE TABLE IF NOT EXISTS price_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_entity_id BIGINT,
    market_id BIGINT,
    remaining_seconds BIGINT,
    up_bid NUMERIC(19, 8),
    up_ask NUMERIC(19, 8),
    up_spread NUMERIC(19, 8),
    down_bid NUMERIC(19, 8),
    down_ask NUMERIC(19, 8),
    down_spread NUMERIC(19, 8),
    captured_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_price_snapshots_market_entity
        FOREIGN KEY (market_entity_id) REFERENCES markets(id)
);
