CREATE TABLE IF NOT EXISTS market_depth_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_entity_id BIGINT,
    market_id BIGINT,
    remaining_seconds BIGINT,
    outcome VARCHAR(128),
    token_id VARCHAR(128),
    best_bid NUMERIC(19, 8),
    best_ask NUMERIC(19, 8),
    spread NUMERIC(19, 8),
    bid_depth NUMERIC(19, 8),
    ask_depth NUMERIC(19, 8),
    near_bid_depth NUMERIC(19, 8),
    near_ask_depth NUMERIC(19, 8),
    depth_imbalance NUMERIC(19, 8),
    near_depth_imbalance NUMERIC(19, 8),
    estimate_buy_usd NUMERIC(19, 8),
    estimate_buy_filled_shares NUMERIC(19, 8),
    estimate_buy_average_price NUMERIC(19, 8),
    estimate_buy_worst_price NUMERIC(19, 8),
    estimate_buy_complete BOOLEAN,
    estimate_buy_levels_consumed INTEGER,
    book_age_ms BIGINT,
    stale BOOLEAN,
    book_updated_at TIMESTAMP,
    captured_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_market_depth_snapshots_market_captured
    ON market_depth_snapshots (market_id, captured_at);

CREATE INDEX IF NOT EXISTS idx_market_depth_snapshots_token_captured
    ON market_depth_snapshots (token_id, captured_at);
